### ISSUE TITLE
用户系统 1

### ISSUE THREAD

**Issue by lepture** [pythoncn/feedbundle#2]
1. 申请
2. 登录
3. 登出

考虑需要哪些数据

**Comment by tonyseek** [comment]
> 1. 申请

是打算用邀请注册机制吗？

**Comment by tonyseek** [comment]
能否具体描述一下打算采取哪种用户管理机制？自助激活还是别的什么？

我打算接下这个 issue。

**Comment by lepture** [comment]
@tonyseek 自助。

另外， @tonyseek 主导一下项目吧。

**Comment by tonyseek** [comment]
@lepture 我怕我的时间有点纠结啊，我现在在实习，基本周末才又空闲时间参与。
