### ISSUE TITLE
抓取 feed

### ISSUE THREAD

**Issue by lepture** [pythoncn/feedbundle#4]
/fetch/{{id}}  抓取 feed，获得文章，将文章存储。

考虑存储什么数据，如何与 bundle 关联。

**Comment by ibigbug** [comment]
标题(原文章链接)
作者 published_time  updated_time
内容
最基本的吧

**Comment by kitelife** [comment]
我觉得不用抓取正文吧...只要有标题，文章链接，作者，时间就OK了吧

**Comment by ibigbug** [comment]
抓正文可以一定程度上解决墙的问题吧。。这样别人就不用点到出处去看了

**Comment by lepture** [comment]
@youngsterxyf 需要做 feed 集合输出的。所以有正文。

**Comment by kitelife** [comment]
@lepture 哦。我不太清楚的一点是各个网站博客的feed应该是不一样的吧，那样的话是不是要分别写解析规则？

**Comment by ibigbug** [comment]
@youngsterxyf 是一样的啊 有Atom和Rss标准啊 feedparser

**Comment by kitelife** [comment]
@ibigbug 哦，这样的啊，这个我不太懂...谢谢！
