### ISSUE TITLE
规范讨论

### ISSUE THREAD

**Issue by lepture** [pythoncn/feedbundle#6]
暂时写了两点规范，大家讨论一下，看不否合适。

https://github.com/pythoncn/feedbundle/wiki/Python-Style-Guide

https://github.com/pythoncn/feedbundle/wiki/Development

**Comment by tonyseek** [comment]
作为一个 `PEP 8` 强迫症患者，非常赞成 : )

建议 flake8 检查代码风格的 wiki 补充一点，推荐大家使用 git hook 提交前拦截检查一次。

另外关于测试用例的编写需要制定规范吗？

**Comment by goofansu** [comment]
第一次用github协同工作，平时都是当仓库自己使用的，还请多多指教

**Comment by tonyseek** [comment]
> 建立自己 id 的 branch，在这个 branch 中开发

貌似分支更适合做 feature 的开发吧，如果是为了区分开发者，那让我们把版本库 Fork 到自己帐户下，开发完再提交 Pull Request 不是更好吗？

**Comment by lepture** [comment]
@tonyseek 其实我是想直接都在 develop 分支上做开发，不用发 pull request 来着。不过 feature 做分支也很好。可以自己编辑 wiki 的。

**Comment by xowenx** [comment]
<del>flask8</del> flake8 检查用pylint最方便吧

更倾向分支开发再发pull request，@lepture 定的就类似feature开发，request后再做code review，满好的。

不过话说回来开始就没有开这个organization的必要了。= =

**Comment by lepture** [comment]
@xowenx 是 flake8 。`sudo pip install flake8`

http://pypi.python.org/pypi/flake8
